# 线上配置文件
server:
  port: 8102
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.132:3306/project_bi
    username: root
    password: pulang662607
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 3
    host: 192.168.50.132
    port: 6379
    password: pulang662607
    timeout: 5000
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # rabbitmq 配置
  # todo 需替换配置，然后取消注释
  rabbitmq:
    host: 192.168.50.132
    port: 5672
    username: admin
    password: pulang662607
  data:
    mongodb:
      uri: mongodb://192.168.50.132:27017/project-bi
