# 线上配置文件
server:
  port: 8102
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.132:3306/project_bi
    username: root
    password: 12345678
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 3
    host: 192.168.50.132
    port: 6379
    timeout: 5000
  # rabbitmq 配置
  # todo 需替换配置，然后取消注释
  rabbitmq:
    host: 192.168.50.132
    port: 5672
    username: admin
  data:
    mongodb:
      uri: mongodb://192.168.50.132:27017/project-bi
